name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Repository auschecken
        uses: actions/checkout@v3

      - name: 📦 Node.js installieren
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📥 Abhängigkeiten installieren & App bauen
        run: |
          cd music-quiz
          npm install
          npm run build

      - name: 🚀 Deploy zu Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "music-quiz"  # Ordner der React-App
          output_location: "music-quiz/build" # Output-Ordner nach Build
          api_location: "music-quiz/server"  # Kein Backend notwendig für Static Web Apps
